### ISSUE TITLE
It asked me to contact the author, so...

### ISSUE THREAD

**Issue by FCO** [kjkuan/Shell-DSL#1]
⚙ fernando@MBP-de-Fernando  ~  zef install Shell::DSL
===> Searching for: Shell::DSL
===> Updating fez mirror: http://360.zef.pm/
===> Updating cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
===> Updating p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json
===> Updated fez mirror: http://360.zef.pm/
===> Updated p6c mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/p6c1.json
===> Updated cpan mirror: https://raw.githubusercontent.com/ugexe/Perl6-ecosystems/master/cpan1.json
===> Searching for missing dependencies: Fcntl:auth<github:kjkuan>
===> Building: Fcntl:ver<0.0.1>:auth<github:kjkuan>
[Fcntl] Apple clang version 12.0.5 (clang-1205.0.22.9)
[Fcntl] Target: x86_64-apple-darwin20.6.0
[Fcntl] Thread model: posix
[Fcntl] InstalledDir: /Library/Developer/CommandLineTools/usr/bin
[Fcntl]  "/Library/Developer/CommandLineTools/usr/bin/clang" -cc1 -triple x86_64-apple-macosx11.0.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -Werror=implicit-function-declaration -emit-obj -disable-free -disable-llvm-verifier -discard-value-names -main-file-name just-for-tests.c -mrelocation-model pic -pic-level 2 -mframe-pointer=all -fno-strict-return -mdisable-tail-calls -fno-rounding-math -munwind-tables -target-sdk-version=11.3 -fvisibility-inlines-hidden-static-local-var -target-cpu penryn -debugger-tuning=lldb -target-linker-version 650.9 -v -resource-dir /Library/Developer/CommandLineTools/usr/lib/clang/12.0.5 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I src -D NDEBUG -D _DARWIN_USE_64_BIT_INODE=1 -D MVM_HEAPSNAPSHOT_FORMAT=2 -I/usr/local/include -internal-isystem /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/local/include -internal-isystem /Library/Developer/CommandLineTools/usr/lib/clang/12.0.5/include -internal-externc-isystem /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -internal-externc-isystem /Library/Developer/CommandLineTools/usr/include -O3 -Wno-logical-op-parentheses -Wno-reorder-init-list -Wno-implicit-int-float-conversion -Wno-c99-designator -Wno-final-dtor-non-final-class -Wno-extra-semi-stmt -Wno-misleading-indentation -Wno-quoted-include-in-framework-header -Wno-implicit-fallthrough -Wno-enum-enum-conversion -Wno-enum-float-conversion -Wno-elaborated-enum-base -fdebug-compilation-dir /Users/fernando/.zef/store/perl6-Fcntl.git/bcf87f521e90eaab845e73949282e5eed0b6377e -ferror-limit 19 -stack-protector 1 -fstack-check -mdarwin-stkchk-strong-link -fblocks -fencode-extended-block-signature -fregister-global-dtors-with-atexit -fgnuc-version=4.2.1 -fmax-type-align=16 -fcommon -vectorize-loops -vectorize-slp -clang-vendor-feature=+disableNonDependentMemberExprInCurrentInstantiation -fno-odr-hash-protocols -mllvm -disable-aligned-alloc-awareness=1 -o src/just-for-tests.o -x c src/just-for-tests.c
[Fcntl] clang -cc1 version 12.0.5 (clang-1205.0.22.9) default target x86_64-apple-darwin20.6.0
[Fcntl] ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/local/include"
[Fcntl] ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/Library/Frameworks"
[Fcntl] #include "..." search starts here:
[Fcntl] #include <...> search starts here:
[Fcntl]  src
[Fcntl]  /usr/local/include
[Fcntl]  /Library/Developer/CommandLineTools/usr/lib/clang/12.0.5/include
[Fcntl]  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include
[Fcntl]  /Library/Developer/CommandLineTools/usr/include
[Fcntl]  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks (framework directory)
[Fcntl] End of search list.
[Fcntl] Apple clang version 12.0.5 (clang-1205.0.22.9)
[Fcntl] Target: x86_64-apple-darwin20.6.0
[Fcntl] Thread model: posix
[Fcntl] InstalledDir: /Library/Developer/CommandLineTools/usr/bin
[Fcntl]  "/Library/Developer/CommandLineTools/usr/bin/clang" -cc1 -triple x86_64-apple-macosx11.0.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -Werror=implicit-function-declaration -emit-obj -disable-free -disable-llvm-verifier -discard-value-names -main-file-name P6-Fcntl.c -mrelocation-model pic -pic-level 2 -mframe-pointer=all -fno-strict-return -mdisable-tail-calls -fno-rounding-math -munwind-tables -target-sdk-version=11.3 -fvisibility-inlines-hidden-static-local-var -target-cpu penryn -debugger-tuning=lldb -target-linker-version 650.9 -v -resource-dir /Library/Developer/CommandLineTools/usr/lib/clang/12.0.5 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I src -D NDEBUG -D _DARWIN_USE_64_BIT_INODE=1 -D MVM_HEAPSNAPSHOT_FORMAT=2 -I/usr/local/include -internal-isystem /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/local/include -internal-isystem /Library/Developer/CommandLineTools/usr/lib/clang/12.0.5/include -internal-externc-isystem /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -internal-externc-isystem /Library/Developer/CommandLineTools/usr/include -O3 -Wno-logical-op-parentheses -Wno-reorder-init-list -Wno-implicit-int-float-conversion -Wno-c99-designator -Wno-final-dtor-non-final-class -Wno-extra-semi-stmt -Wno-misleading-indentation -Wno-quoted-include-in-framework-header -Wno-implicit-fallthrough -Wno-enum-enum-conversion -Wno-enum-float-conversion -Wno-elaborated-enum-base -fdebug-compilation-dir /Users/fernando/.zef/store/perl6-Fcntl.git/bcf87f521e90eaab845e73949282e5eed0b6377e -ferror-limit 19 -stack-protector 1 -fstack-check -mdarwin-stkchk-strong-link -fblocks -fencode-extended-block-signature -fregister-global-dtors-with-atexit -fgnuc-version=4.2.1 -fmax-type-align=16 -fcommon -vectorize-loops -vectorize-slp -clang-vendor-feature=+disableNonDependentMemberExprInCurrentInstantiation -fno-odr-hash-protocols -mllvm -disable-aligned-alloc-awareness=1 -o src/P6-Fcntl.o -x c src/P6-Fcntl.c
[Fcntl] clang -cc1 version 12.0.5 (clang-1205.0.22.9) default target x86_64-apple-darwin20.6.0
[Fcntl] ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/local/include"
[Fcntl] ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/Library/Frameworks"
[Fcntl] #include "..." search starts here:
[Fcntl] #include <...> search starts here:
[Fcntl]  src
[Fcntl]  /usr/local/include
[Fcntl]  /Library/Developer/CommandLineTools/usr/lib/clang/12.0.5/include
[Fcntl]  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include
[Fcntl]  /Library/Developer/CommandLineTools/usr/include
[Fcntl]  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks (framework directory)
[Fcntl] End of search list.
[Fcntl] Apple clang version 12.0.5 (clang-1205.0.22.9)
[Fcntl] Target: x86_64-apple-darwin20.6.0
[Fcntl] Thread model: posix
[Fcntl] InstalledDir: /Library/Developer/CommandLineTools/usr/bin
[Fcntl]  "/Library/Developer/CommandLineTools/usr/bin/ld" -demangle -lto_library /Library/Developer/CommandLineTools/usr/lib/libLTO.dylib -dynamic -dylib -arch x86_64 -platform_version macos 11.0.0 11.3 -syslibroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -o resources/lib/libjust-for-tests.dylib -L/usr/local/lib -rpath @executable_path/../lib src/just-for-tests.o src/P6-Fcntl.o -lc -lSystem /Library/Developer/CommandLineTools/usr/lib/clang/12.0.5/lib/darwin/libclang_rt.osx.a
===> Building [OK] for Fcntl:ver<0.0.1>:auth<github:kjkuan>
===> Testing: Fcntl:ver<0.0.1>:auth<github:kjkuan>
===> Testing [OK] for Fcntl:ver<0.0.1>:auth<github:kjkuan>
===> Testing: Shell::DSL:ver<0.0.1>:auth<Jack Kuan (kjkuan@gmail.com)>
[Shell::DSL] An operation first awaited:
[Shell::DSL]   in method run at /Users/fernando/.zef/store/Shell-DSL.git/a1f0807490dd5259438b14b798a4de8eb1a7e057/lib/Shell/DSL.rakumod (Shell::DSL) line 405
[Shell::DSL]   in method sink at /Users/fernando/.zef/store/Shell-DSL.git/a1f0807490dd5259438b14b798a4de8eb1a7e057/lib/Shell/DSL.rakumod (Shell::DSL) line 249
[Shell::DSL]   in block <unit> at t/01-basic.t line 21
[Shell::DSL] Died with the exception:
[Shell::DSL]     Cannot look up attributes in a Hash type object
[Shell::DSL]       in block  at /Users/fernando/.zef/store/Shell-DSL.git/a1f0807490dd5259438b14b798a4de8eb1a7e057/lib/Shell/DSL.rakumod (Shell::DSL) line 280
[Shell::DSL] Saw 1 occurrence of deprecated code.
[Shell::DSL] ================================================================================
[Shell::DSL] Method path (from Cool) seen at:
[Shell::DSL]   /Users/fernando/.zef/store/Shell-DSL.git/a1f0807490dd5259438b14b798a4de8eb1a7e057/lib/Shell/DSL.rakumod (Shell::DSL), line 643
[Shell::DSL] Please use IO instead.
[Shell::DSL] --------------------------------------------------------------------------------
[Shell::DSL] Please contact the author to have these occurrences of deprecated code
[Shell::DSL] adapted, so that this message will disappear!
===> Testing [FAIL]: Shell::DSL:ver<0.0.1>:auth<Jack Kuan (kjkuan@gmail.com)>
Aborting due to test failure: Shell::DSL:ver<0.0.1>:auth<Jack Kuan (kjkuan@gmail.com)> (use --force-test to override)

**Comment by kjkuan** [comment]
Thanks. I just started getting back to playing with Raku yesterday. I believe I've fixed the deprecation warning as well as the failed test caused by the Hash type object.

**Comment by FCO** [comment]
Thanks!
